name: tsne-paper
channels:
  - defaults
dependencies:
  - pip=21.2.4
  - python=3.10
  - hdf5=1.12.1
  - pip:
      - anndata==0.8.0
      - blosc2==2.0.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - cython==3.0.0
      - fonttools==4.42.1
      - h5py==3.9.0
      - joblib==1.3.2
      - kiwisolver==1.4.4
      - llvmlite==0.40.1
      - matplotlib==3.5.1
      - msgpack==1.0.5
      - natsort==8.4.0
      - networkx==2.7.1
      - numba==0.57.1
      - numexpr==2.8.5
      - numpy==1.24.2
      - opentsne==0.6.2
      - packaging==23.1
      - pandas==1.4.1
      - patsy==0.5.3
      - pillow==10.0.0
      - py-cpuinfo==9.0.0
      - pynndescent==0.5.6
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - pytz==2023.3
      - scanpy==1.8.2
      - scikit-learn==1.1.2
      - scipy==1.8.0
      - seaborn==0.12.2
      - sinfo==0.3.4
      - six==1.16.0
      - statsmodels==0.13.2
      - stdlib-list==0.9.0
      - tables==3.7.0
      - threadpoolctl==3.2.0
      - tqdm==4.66.1
      - umap-learn==0.5.2
